### ISSUE TITLE
Hard coded redis service name

### ISSUE THREAD

**Issue by Maniacal** [apigee/pivotal-cf-apigee#20]
https://github.com/apigee/pivotal-cf-apigee/blob/master/apigee-cf-service-broker/helpers/datastore.js#L36

I know the instructions say to use the name that's hardcoded but I wasn't able.

**Comment by carloseberhardt** [comment]
Can you explain a bit more why it didn't work? Want to understand the issue so we can try to find appropriate resolution.

**Comment by carloseberhardt** [comment]
Latest version of the broker eliminates the need for the redis store, so if you grab the latest you won't need this service.

**Comment by Maniacal** [comment]
I missed your last message.  Sorry about that.  I'll be taking this back up this week so good timing :).   I'll verify and will let you know.

**Comment by Maniacal** [comment]
Based on your last comment I'm going to close this.  Thanks.
