### ISSUE TITLE
Bind route service fails with json error

### ISSUE THREAD

**Issue by arghya88** [apigee/pivotal-cf-apigee#31]
Trying to run below command : 

```
cf bind-route-service <your-app-domain> <service-instance> [--hostname <hostname>] \
 -c '{"org":"<your edge org>","env":"<your edge env>",
    "<username>:<password>",
    "action":"proxy bind",
    ["protocol":"https"]}'
```

Fails with below error:

`json: error calling MarshalJSON for type *json.RawMessage: invalid character ',' after object key`

**Comment by kenigeer** [comment]
Looks like there is a mistake in the docs. If you must specify the credentials in clear text, there are two separate keys: "user" and "pass". So instead of the single string

    "<username>:<password>",

(which, as the error says, is not valid JSON anyway) you need two JSON pairs:

    "user":"<username>", "pass":"<password>",

**Comment by arghya88** [comment]
@kenigeer
I will try this and update here
Thanks,
Arghya
